name: Swift

on:
  pull_request:
    branches: [ master ]
  create:
    branches: [ master ]
    
jobs:    
  test:
    name: Test
    runs-on: macos-lasted

    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
