name: Swift

on:
  pull_request:
    branches: [ master ]
  create:
    branches: [ master ]
    
jobs:    
  test:
    name: Test
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Bundle Install
      run: bundle install
    - name: Unit tests
      run: bundle exec fastlane tests schemeToChange:"Calculator Project"
